#!/bin/sh

case "$1" in
    start)
        echo "starting tuxpresso..."

        GPIO=17
        IIO=0

        # Initialize the IIO temperature sensor
        modprobe i2c-bcm2835
        modprobe i2c-dev
        modprobe mcp9600
        echo mcp9600 0x60 > /sys/class/i2c-adapter/i2c-1/new_device

        # Initialize the boiler GPIO
        echo $GPIO > /sys/class/gpio/export
        echo out > /sys/class/gpio/gpio$GPIO/direction

        boilerd \
            -g $GPIO \
            -i $IIO \
            -sp 1632 \
            -kp 64 \
            -ki 1 \
            -kd 0 \
            -max 2000 \
            2>> /var/log/boilerd &
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
