#!/bin/sh

case "$1" in
    start)
        mount /dev/mmcblk0p1 /mnt
        cp /mnt/wpa_supplicant.conf /etc/wpa_supplicant.conf
        mkdir -p /root/.ssh
        cp /mnt/authorized_keys /root/.ssh/authorized_keys
        umount /mnt
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
