BOILERD_VERSION = e1dd418643e7f82e0ea1eaeb02040bd3850ef024
BOILERD_SITE = $(call github,tuxpresso,boilerd,$(BOILERD_VERSION))
BOILERD_LICENSE = GPL-2.0
BOILERD_LICENSE_FILES = COPYING
BOILERD_INSTALL_STAGING = YES
BOILERD_INSTALL_TARGET = YES
BOILERD_DEPENDENCIES = pidc

define BOILERD_BUILD_CMDS
	$(MAKE) CC="$(TARGET_CC)" LD="$(TARGET_LD)" -C $(@D)
endef

define BOILERD_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/boilerd $(TARGET_DIR)/usr/bin
endef

$(eval $(generic-package))
